id = "jsonp"
name = "JSONP"
version = "0.0.1"
schema_version = 1
authors = ["colton murphy"]
description = "Syntax highlighting for the jsonp format"
repository = "https://github.com/LostTime76/zed-jsonp"

[grammars.jsonp]
repository = "https://github.com/LostTime76/tree-sitter-jsonp"
commit = "df5ad87476bacf04775a316d93b65fd79df797cc"
