id = "jsonp"
name = "JSONP"
version = "0.0.1"
schema_version = 1
authors = ["colton murphy"]
description = "Syntax highlighting for the jsonp format"
repository = "https://github.com/LostTime76/zed-jsonp"

[grammars.jsonp]
repository = "https://github.com/LostTime76/tree-sitter-jsonp"
commit = "e405b7037cded4d4a4533c5d4be7cccf627e2fb3"
